---

- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    yum:
      name: httpd
      state: latest

  - name: Update cache
    yum:
      update_cache: yes

  - name: PHP support for apache
    yum:
      name: php
      state: latest
